spring.application.name=backend


# DATABASE
spring.datasource.url=jdbc:postgresql://localhost:5432/legal_ai_db
spring.datasource.username=postgres
spring.datasource.password=DIYA@2004
# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# SERVER
server.port=8080

#Spring Security
spring.security.user.name=admin
spring.security.user.password=admin

# JWT
jwt.secret=yourSuperSecretKeyForJwtTokenGeneration123456
jwt.expiration=86400000

# AI MODEL
ai.model.url=http://localhost:5000/predict