spring.application.name=backend


# DATABASE
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# SERVER
server.port=8080

#Spring Security
spring.security.user.name=admin
spring.security.user.password=admin

# JWT
jwt.secret=yourSuperSecretKeyForJwtTokenGeneration123456
jwt.expiration=86400000

# AI MODEL
ai.model.url=${AI_MODEL_URL}
